# Generated by Django 2.1.4 on 2018-12-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20181224_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='profile_pic',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
