# Generated by Django 2.1.4 on 2018-12-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLoginTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('user_status', models.CharField(choices=[('active', 'ACTIVE'), ('blocked', 'BLOCKED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('normal', 'Normal'), ('institute_user', 'Institute User'), ('super_admin', 'Super Admin')], default='normal', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userlogintable',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.userTable'),
        ),
    ]
